version: "3.9"

services:
  oauth-authorization-server:    
    build: ./oauth-authorization-server
    ports:
      - "8083:8083"
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin    
      - KEYCLOAK_FRONTEND_URL=http://localhost:8083
    
    
  oauth-client:    
    build: ./spring-boot-keycloak
    depends_on: 
      - oauth-authorization-server
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_ADDRESS=http://oauth-authorization-server:8083/auth
      - KEYCLOAK_REALM=baeldung
      - KEYCLOAK_CLIENT_ID=login-app
    
    
    
